[package]
name = "crossterm-stdin-test"
version = "0.1.0"
authors = ["Tim Buckley <timothy.jas.buckley@hpe.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.10"
